-- MySQL Script generated by MySQL Workbench
-- Wed Oct 22 08:35:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pwa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pwa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pwa` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `pwa` ;

-- -----------------------------------------------------
-- Table `pwa`.`user_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pwa`.`user_types` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pwa`.`user_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name` ON `pwa`.`user_types` (`name` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pwa`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pwa`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pwa`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `birth_date` DATE NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `user_type_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `pwa`.`user_types` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `email` ON `pwa`.`users` (`email` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `cpf` ON `pwa`.`users` (`cpf` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `user_type_id` ON `pwa`.`users` (`user_type_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pwa`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pwa`.`events` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pwa`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `type` VARCHAR(50) NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `is_public` TINYINT(1) NULL DEFAULT '0',
  `groups_combined` TINYINT(1) NULL DEFAULT '0',
  `event_datetime` DATETIME NULL DEFAULT NULL,
  `event_location` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `target_user_types` JSON NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `events_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `pwa`.`users` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `user_id` ON `pwa`.`events` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pwa`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pwa`.`groups` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pwa`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `group_type` ENUM('turma', 'turno', 'area_ensino', 'curso', 'custom') NULL DEFAULT 'custom',
  `created_by` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `groups_ibfk_1`
    FOREIGN KEY (`created_by`)
    REFERENCES `pwa`.`users` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `created_by` ON `pwa`.`groups` (`created_by` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pwa`.`event_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pwa`.`event_groups` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pwa`.`event_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `event_groups_ibfk_1`
    FOREIGN KEY (`event_id`)
    REFERENCES `pwa`.`events` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `event_groups_ibfk_2`
    FOREIGN KEY (`group_id`)
    REFERENCES `pwa`.`groups` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `event_id` ON `pwa`.`event_groups` (`event_id` ASC, `group_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `group_id` ON `pwa`.`event_groups` (`group_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pwa`.`guardians`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pwa`.`guardians` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pwa`.`guardians` (
  `guardian_id` INT NOT NULL,
  `relationship` VARCHAR(50) NULL DEFAULT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`guardian_id`),
  CONSTRAINT `guardians_ibfk_1`
    FOREIGN KEY (`guardian_id`)
    REFERENCES `pwa`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `guardians_ibfk_2`
    FOREIGN KEY (`student_id`)
    REFERENCES `pwa`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `student_id` ON `pwa`.`guardians` (`student_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pwa`.`permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pwa`.`permissions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pwa`.`permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_type_id` INT NOT NULL,
  `can_create_event` TINYINT(1) NULL DEFAULT '0',
  `can_view_all_events` TINYINT(1) NULL DEFAULT '0',
  `can_receive_notifications` TINYINT(1) NULL DEFAULT '1',
  `can_create_user` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  CONSTRAINT `permissions_ibfk_1`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `pwa`.`user_types` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `user_type_id` ON `pwa`.`permissions` (`user_type_id` ASC) VISIBLE;

SHOW WARNINGS;
-- Note: previous model included a separate table `push_subscriptions`.
-- The project now consolidates push subscriptions into the `subscriptions` table.
-- The legacy `push_subscriptions` creation has been removed to avoid creating
-- duplicate storage during deploy. If you have existing data in an old
-- database, run the consolidation migration `backend/migrations/003-consolidate-subscriptions.sql`.

-- -----------------------------------------------------
-- Table `pwa`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pwa`.`students` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pwa`.`students` (
  `student_id` INT NOT NULL,
  `class` VARCHAR(50) NULL DEFAULT NULL,
  `registration_number` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`student_id`),
  CONSTRAINT `students_ibfk_1`
    FOREIGN KEY (`student_id`)
    REFERENCES `pwa`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `registration_number` ON `pwa`.`students` (`registration_number` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pwa`.`subscriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pwa`.`subscriptions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pwa`.`subscriptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `endpoint` TEXT NOT NULL,
  `keys_p256dh` TEXT NOT NULL,
  `keys_auth` TEXT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `subscriptions_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `pwa`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `user_id` ON `pwa`.`subscriptions` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pwa`.`teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pwa`.`teachers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pwa`.`teachers` (
  `teacher_id` INT NOT NULL,
  `courses` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`teacher_id`),
  CONSTRAINT `teachers_ibfk_1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `pwa`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pwa`.`user_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pwa`.`user_groups` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pwa`.`user_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `joined_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `user_groups_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `pwa`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `user_groups_ibfk_2`
    FOREIGN KEY (`group_id`)
    REFERENCES `pwa`.`groups` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `user_id` ON `pwa`.`user_groups` (`user_id` ASC, `group_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `group_id` ON `pwa`.`user_groups` (`group_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Seed mínimo e notas de deploy
-- -----------------------------------------------------
-- Insere tipos de usuário padrão (ignora se já existirem)
INSERT IGNORE INTO `pwa`.`user_types` (`name`, `description`) VALUES
  ('student', 'Estudante'),
  ('teacher', 'Professor'),
  ('admin', 'Administrador'),
  ('guardian', 'Responsável');

-- Insere permissões padrão para cada tipo de usuário se ainda não existir
INSERT INTO `pwa`.`permissions` (`user_type_id`, `can_create_event`, `can_view_all_events`, `can_receive_notifications`, `can_create_user`)
SELECT ut.id,
       CASE WHEN ut.name IN ('teacher','admin') THEN 1 ELSE 0 END,
       CASE WHEN ut.name = 'admin' THEN 1 ELSE 0 END,
       1,
       CASE WHEN ut.name = 'admin' THEN 1 ELSE 0 END
FROM `pwa`.`user_types` ut
WHERE ut.name IN ('student','teacher','admin','guardian')
  AND NOT EXISTS (SELECT 1 FROM `pwa`.`permissions` p WHERE p.user_type_id = ut.id);

-- Nota: existem duas tabelas relacionadas a subscriptions para compatibilidade:
-- `push_subscriptions` e `subscriptions`. Considere consolidá-las em uma
-- única tabela em uma migração futura para evitar duplicidade. Ambas foram
-- mantidas aqui para compatibilidade com o código atual.

-- Nota: o arquivo `frontend/public/service-worker.js` deve ser servido na raiz do
-- domínio como `/service-worker.js` após o deploy. Garanta que o servidor copie
-- ou sirva esse arquivo corretamente (ex.: copiar para `build/` ou configurar
-- rota específica no Express).

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
-- Banco de dados para o sistema de eventos escolares
-- Utilize: USE pwa; antes de executar

USE pwa;

-- Tabela de tipos de usuários (flexível para novos perfis)
CREATE TABLE user_types (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL UNIQUE, -- Ex: student, teacher, admin
    description TEXT
);

-- Tabela de permissões por tipo de usuário
CREATE TABLE permissions (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_type_id INT NOT NULL,
    can_create_event BOOLEAN DEFAULT FALSE,
    can_view_all_events BOOLEAN DEFAULT FALSE,
    can_receive_notifications BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (user_type_id) REFERENCES user_types(id) ON DELETE CASCADE
);

-- Tabela de usuários (centraliza todos os tipos)
CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20),
    birth_date DATE,
    password VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    user_type_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_type_id) REFERENCES user_types(id) ON DELETE RESTRICT
);

-- Tabela de estudantes
CREATE TABLE students (
    student_id INT PRIMARY KEY,
    class VARCHAR(50),
    registration_number VARCHAR(20) UNIQUE,
    FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Tabela de professores
CREATE TABLE teachers (
    teacher_id INT PRIMARY KEY,
    courses VARCHAR(255),
    FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Tabela de responsáveis
CREATE TABLE guardians (
    guardian_id INT PRIMARY KEY,
    relationship VARCHAR(50),
    student_id INT NOT NULL,
    FOREIGN KEY (guardian_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Tabela de eventos
CREATE TABLE events (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(100) NOT NULL,
    description TEXT,
    type VARCHAR(50),
    user_id INT,
    is_public BOOLEAN DEFAULT FALSE,
    groups_combined BOOLEAN DEFAULT FALSE, -- Indica se múltiplos grupos são combinados (AND) ou não (OR)
    event_datetime DATETIME,
    event_location VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Tabela de assinaturas para notificações push
CREATE TABLE subscriptions (
    id INT PRIMARY KEY AUTO_INCREMENT,
    endpoint TEXT NOT NULL,
    keys_p256dh TEXT NOT NULL,
    keys_auth TEXT NOT NULL,
    user_id INT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Tabela de grupos (para organizar usuários em grupos específicos)
CREATE TABLE `groups` (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    group_type ENUM('turma', 'turno', 'area_ensino', 'curso', 'custom') DEFAULT 'custom',
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

-- Tabela de relacionamento entre usuários e grupos
CREATE TABLE user_groups (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    group_id INT NOT NULL,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, group_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (group_id) REFERENCES `groups`(id) ON DELETE CASCADE
);

-- Tabela de relacionamento entre eventos e grupos
CREATE TABLE event_groups (
    id INT PRIMARY KEY AUTO_INCREMENT,
    event_id INT NOT NULL,
    group_id INT NOT NULL,
    UNIQUE(event_id, group_id),
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    FOREIGN KEY (group_id) REFERENCES `groups`(id) ON DELETE CASCADE
);

-- Tabela de notificações agendadas (fila de envio de push)
-- Campos adicionais: attempts (número de tentativas), last_error (último erro registrado)
CREATE TABLE scheduled_notifications (
  id INT PRIMARY KEY AUTO_INCREMENT,
  event_id INT NOT NULL,
  payload JSON NOT NULL,
  scheduled_at DATETIME NOT NULL,
  sent TINYINT(1) DEFAULT 0,
  attempts INT DEFAULT 0,
  last_error TEXT NULL,
  last_attempt_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
);